[package]
name = "wpaperctl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wpaperd-ipc = { path = "../ipc" }
clap = { version = "4.5.3", features = ["derive", "wrap_help"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[build-dependencies]
clap = { version = "4.5.3", features = ["derive", "cargo"] }
clap_complete = "4.5.1"
clap_mangen = "0.2.20"
